# Configuration
permalink:           pretty
highlighter:         rouge
markdown:            kramdown
markdown_ext:        markdown,mkdown,mkdn,mkd,md

# Setup
title:               Corralx
tagline:             My slice of reality
url:                 https://corralx.github.io
repo:                https://github.com/corralx/corralx.github.io
paginate:            3
baseurl:             ""
excerpt_separator:   <!--more-->

# Sass
sass:
  sass_dir:          _sass
  style:             compressed

# About/contact
author:
  name:              Matteo Bertello
  username:          Corralx
  email:             bertello.matteo@gmail.com
  github:            corralx
  twitter:           corralx
  stackoverflow:     4141391
  stackexchange:     368929
  linkedin:          matteo-bertello-06538017

collections:
  projects:
    output: true
  timeline:
    output: false

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Exclude from conversion
exclude: [.gitignore, CNAME, LICENSE.md, README.md, TODO.md]
